# Generated by Django 5.2.7 on 2025-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Manager', max_length=250),
        ),
    ]
